#!/bin/bash
#
# Author      : Kuba Sejdak <kuba.sejdak@gmail.com>
# Description : Starts debugging session for STM32Discovery.

FLIGHTCONTROLLER_GDBINIT_PATH="$QUADCOPTER_PATH/flight-controller/board/stm32f4_discovery/stm32f4_discovery.gdbinit"

arm-none-eabi-gdb --tui $FLIGHTCONTROLLER_FIRMWARE_PATH -x ./test
