#!/bin/bash
#
# Author      : Kuba Sejdak <kuba.sejdak@gmail.com>
# Description : Starts debugging session for STM32Discovery.
#
# $1 - project to debug

if [ -z $1 ]; then
	echo "No project provided. Abort."
	exit 1
fi

# Remove trailing slash if present
PROJECT=$1
if [ "${PROJECT: -1}" ==  "/" ]; then
	PROJECT=`echo $1 | rev | cut -c 2- | rev`
fi

cgdb -d arm-none-eabi-gdb -- $PROJECT/bin/$PROJECT.elf -x stm32f4_discovery.gdbinit
#arm-none-eabi-gdb --tui $PROJECT/bin/$PROJECT.elf -x stm32f4_discovery.gdbinit
