#!/bin/bash
#
# Author      : Kuba Sejdak <kuba.sejdak@gmail.com>
# Description : Starts OpenOCD debugging session.

openocd -f /usr/share/openocd/scripts/board/stm32f4discovery.cfg -c "init" -c "reset halt"
